### ISSUE TITLE
feat: add article PWA with authentication

### ISSUE THREAD

**Issue by johnborges** [microsoft/win-student-devs#52]
# Proposal: Add article explaining PWA with some authentication integration 

## Description
Most real world applications have an authentication step before the user can use the application. It would be helpful to include an article explaining a simple example of this. Possibly using OAuth or a PWA behind cookie authentication.

## Rationale
Showing examples of this I think would improve real world PWA adoption.

**Comment by beth-panx** [comment]
Hi @johnborges - [this article](https://microsoft.github.io/win-student-devs/#/30DaysOfPWA/platforms-practices/06) is scheduled for 3/12 and will be authored by @nmetulev
