### ISSUE TITLE
Publicize the availability of the RSS feed

### ISSUE THREAD

**Issue by tomayac** [microsoft/win-student-devs#71]
As a quick follow-up to #32, you want to publicize the feed's existence.

- Add… 

  ```html
   <link rel="alternate"
            type="application/atom+xml"
            title="RSS Feed for #30DaysOfPWA"
            href="https://microsoft.github.io/win-student-devs/feed.xml"
   />
   ```

   …to all the pages (or page templates).
- Add a regular user-visible link…

   ```html
   <a href="https://microsoft.github.io/win-student-devs/feed.xml">
     RSS feed
   </a>
   ```
 
   …to all the pages (or page templates).

**Comment by beth-panx** [comment]
Hi @tomayac - I added something similar to the index page in this pr #70. Probably also need to add the link on the site to make this feature visible.
